import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import unusedImports from 'eslint-plugin-unused-imports';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import prettier from 'eslint-plugin-prettier';
import eslintConfigPrettier from 'eslint-config-prettier';
import vue from 'eslint-plugin-vue';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.turbo/**',
      '**/.quasar/**',
      '**/src-capacitor/**',
      '**/src-electron/**',
      '**/*.tsbuildinfo',
      '.eslintrc.js',
      'commitlint.config.js',
      'vitest.config.ts',
      'vite.config.ts',
      '**/quasar.config.js',
      '**/quasar.config.cjs',
      '**/quasar.config.cjs.temporary.compiled.*.cjs',
      '**/postcss.config.js',
      '**/src-ssr/**',
      '**/public/argon2-bundled.min.js',
      'apps/client/src/**/*.d.ts',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'unused-imports': unusedImports,
      'simple-import-sort': simpleImportSort,
      prettier,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          varsIgnorePattern: '^_',
          args: 'after-used',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-restricted-types': 'off',
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { disallowTypeAnnotations: false },
      ],
      'prettier/prettier': ['error', { endOfLine: 'auto' }],
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
    },
  },
  // Client app: globals auto-importés par unplugin-auto-import (quasar.config.cjs)
  {
    files: ['apps/client/**/*.{vue,ts,js}'],
    languageOptions: {
      globals: {
        ga: 'readonly',
        cordova: 'readonly',
        __statics: 'readonly',
        __QUASAR_SSR__: 'readonly',
        __QUASAR_SSR_SERVER__: 'readonly',
        __QUASAR_SSR_CLIENT__: 'readonly',
        __QUASAR_SSR_PWA__: 'readonly',
        Capacitor: 'readonly',
        chrome: 'readonly',
        mainLogger: 'readonly',
        trpcClient: 'readonly',
        internals: 'readonly',
        appStore: 'readonly',
        authStore: 'readonly',
        uiStore: 'readonly',
        pagesStore: 'readonly',
        router: 'readonly',
        route: 'readonly',
        $quasar: 'readonly',
        useMeta: 'readonly',
        CustomDialog: 'readonly',
        onMounted: 'readonly',
        onBeforeMount: 'readonly',
        onBeforeUpdate: 'readonly',
        onUpdated: 'readonly',
        onBeforeUnmount: 'readonly',
        onUnmounted: 'readonly',
        ref: 'readonly',
        computed: 'readonly',
        watch: 'readonly',
        watchEffect: 'readonly',
        watchPostEffect: 'readonly',
        shallowRef: 'readonly',
        triggerRef: 'readonly',
        reactive: 'readonly',
        toRef: 'readonly',
        toRefs: 'readonly',
        unref: 'readonly',
        inject: 'readonly',
        provide: 'readonly',
        nextTick: 'readonly',
        defineComponent: 'readonly',
        defineProps: 'readonly',
        defineEmits: 'readonly',
        defineExpose: 'readonly',
        withDefaults: 'readonly',
        h: 'readonly',
        useRoute: 'readonly',
        useRouter: 'readonly',
        useQuasar: 'readonly',
        Notify: 'readonly',
        Cookies: 'readonly',
        Dialog: 'readonly',
        useDialogPluginComponent: 'readonly',
      },
    },
  },
  // Vue-specific rules for client .vue files (TypeScript in script blocks)
  {
    files: ['apps/client/**/*.vue'],
    plugins: { vue },
    extends: [...vue.configs['flat/essential']],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.vue'],
      },
    },
    rules: {
      'prefer-promise-reject-errors': 'off',
      quotes: ['warn', 'single', { avoidEscape: true }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/await-thenable': 'off',
      '@typescript-eslint/consistent-type-imports': 'off',
      'no-debugger': 'off',
      'vue/multi-word-component-names': 'off',
    },
  },
  eslintConfigPrettier,
);
